use_gpu: True
device: 3
seed: 2 # 2在这里比较ok
early_stop:
  patience: 60
federate:
  mode: standalone
  method: fgpl_worker
  client_num: 10
  sample_client_rate: 1.0
  total_round_num: 200
  make_global_eval: False
fedproto:
  proto_weight: 0.2 # the weight of proto loss;
  show_verbose: False # weather display verbose loss information
  infoNCET: 0.02
  lamda: 0.5 # loss_c+loss_m的权重
graphsha:
  imb_ratio: 90
  gdc: 'ppr'
  warmup: 5
  tau: 2
  beta: 1
data:
  root: data/
  type: citeseer
  splitter: 'louvain'
dataloader:
  type: pyg
  batch_size: 1
MHFL:
  task: node  #TODO: MHFL.task and model.task should only keep one
model:
  type: gcn
  dropout: 0.5
  out_channels: 6
  return_proto: True
  warpFC: True #important
  feature_dim: 64 #important
train:
  local_update_steps: 5
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.1
    weight_decay: 5e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fgpl_trainer_1
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: val_acc
vis_embedding: False
show_client_best_individual: True
show_label_distribution: False
